os: linux

cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor


language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update --stable -n
  - travis_retry composer update  --no-interaction --prefer-source

script: ./vendor/bin/phpunit

notifications:
  email: lessmoredev@gmail.com