os: linux

cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor


language: php

php:
  - 7.1
  - 7.2

install:
  - composer install --no-interaction

script: ./vendor/bin/phpunit

notifications:
  email: lessmoredev@gmail.com